#!/usr/bin/env bash
# Yosys synthesis driver for Vibe-UB-Switch.
# Generates reports under reports/synth/. Does not invent QoR numbers.
#
# Default MEMORY_MAP=0: stop before memory_map so large SAF/VOQ/retry
# arrays stay inferred memories (mapping them to FFs is not honest Sky130
# area and can OOM).
#
# FRONTEND=verilog (default) uses read_verilog -sv.
# FRONTEND=slang uses the yosys-slang plugin without raising unroll-limit
# (do not pass --unroll-limit 200000; that OOMs ~15GB on this chip).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
TOP="${TOP:-vibe_ub_switch}"
INC_DIR="${INC_DIR:-$ROOT/rtl/common}"
RPT_DIR="${RPT_DIR:-$ROOT/reports/synth}"
OUT_DIR="${OUT_DIR:-$ROOT/scripts/synth/work}"
SDC="${SDC:-}"
LIBERTY="${LIBERTY:-}"
YOSYS="${YOSYS:-yosys}"
RTL_SHA="${RTL_SHA:-32a7f5e0c3f04762aa27dae73b000e55773195da}"
MEMORY_MAP="${MEMORY_MAP:-0}"
FRONTEND="${FRONTEND:-verilog}"

if [ "$#" -lt 1 ]; then
  echo "usage: $0 <verilog-file> [verilog-file...]" >&2
  echo "env: TOP INC_DIR RPT_DIR OUT_DIR SDC LIBERTY YOSYS RTL_SHA MEMORY_MAP FRONTEND" >&2
  exit 2
fi

if ! command -v "$YOSYS" >/dev/null 2>&1; then
  cat >&2 <<'EOF'
Yosys not found. Install oss-cad-suite (Yosys 0.54 + slang) or apt yosys.
Do not copy PDK / liberty / LEF binaries into this repo.
EOF
  exit 2
fi

mkdir -p "$RPT_DIR" "$OUT_DIR"

YS="$OUT_DIR/${TOP}.ys"
NETLIST="$OUT_DIR/${TOP}.synth.v"
LOG="$RPT_DIR/synth.log"

{
  echo "# Generated by scripts/synth/yosys/run_synth.sh — do not hand-edit."
  echo "logger -notime"
  echo "echo on"
  if [ "$FRONTEND" = "slang" ]; then
    echo "plugin -i slang"
    # Default slang unroll-limit (4000). Do not raise to 200000.
    printf 'read_slang --single-unit --compat-mode -I %s' "$INC_DIR"
    for f in "$@"; do
      printf ' %s' "$f"
    done
    printf '\n'
  else
    for f in "$@"; do
      printf 'read_verilog -sv -I %s %s\n' "$INC_DIR" "$f"
    done
  fi
  # Coarse synth only (memory -nomap). Stop before fine/memory_map.
  echo "synth -top $TOP -run :fine"
  echo "tee -o $RPT_DIR/hierarchy.rpt stat"
  if [ "$MEMORY_MAP" = "1" ]; then
    echo "memory_map"
    echo "opt -full"
  fi
  echo "opt -fast -full"
  echo "techmap"
  echo "opt -fast"
  if [ -n "$LIBERTY" ]; then
    echo "dfflibmap -liberty $LIBERTY"
    echo "abc -liberty $LIBERTY"
    echo "opt_clean"
    echo "tee -o $RPT_DIR/stat.rpt stat -liberty $LIBERTY"
  else
    echo "tee -o $RPT_DIR/stat.rpt stat"
  fi
  echo "write_verilog -noattr $NETLIST"
} > "$YS"

{
  echo "design              $TOP"
  echo "repo_root           $ROOT"
  echo "repo_sha            $(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
  echo "dut_rtl_sha         $RTL_SHA"
  echo "spec_md_frozen      no"
  echo "tapeout             no"
  echo "yosys               $($YOSYS -V 2>/dev/null | head -n 1 || echo unknown)"
  echo "frontend            $FRONTEND"
  echo "sdc                 ${SDC:-none}"
  echo "liberty             ${LIBERTY:-none (generic cells; not Sky130 area)}"
  echo "memory_map          $MEMORY_MAP"
  echo "netlist             $NETLIST"
  echo "platform            sky130hd (ORFS name; only if liberty was provided)"
  echo "note                Sky130 cannot close spec 1.25 GHz. Methodology QoR only."
  echo "top_mapped          no  (block-level only; full-chip slang OOM/unroll)"
} > "$RPT_DIR/flow_info.txt"

set +e
"$YOSYS" -s "$YS" > "$LOG" 2>&1
ys_rc=$?
set -e

if [ -f "$RPT_DIR/stat.rpt" ]; then
  grep -E 'Number of |Chip area|Estimated number of LCs|wires:|cells:|[[:space:]]+\$_|[[:space:]]+\$mem|[[:space:]]+sky130_' \
    "$RPT_DIR/stat.rpt" > "$RPT_DIR/cells.rpt" || true
  if grep -q 'Chip area' "$RPT_DIR/stat.rpt"; then
    grep -E 'Chip area|Number of cells|Number of memories' "$RPT_DIR/stat.rpt" > "$RPT_DIR/area.rpt"
    echo "NOTE: Chip area is stdcell-only if memories were left unmapped (MEMORY_MAP=$MEMORY_MAP)." >> "$RPT_DIR/area.rpt"
  else
    cat > "$RPT_DIR/area.rpt" <<EOF
STATUS: generic_synth
NOTE: No liberty was passed to Yosys, so there is no Sky130 area figure.
      Cell counts are in $RPT_DIR/stat.rpt / cells.rpt.
EOF
  fi
else
  echo "STATUS: synth_failed" > "$RPT_DIR/area.rpt"
  echo "STATUS: synth_failed" > "$RPT_DIR/cells.rpt"
fi

cat > "$RPT_DIR/timing_summary.rpt" <<EOF
STATUS: not_run_by_yosys
NOTE: Yosys synth does not produce WNS/TNS. OpenSTA was not run (no mapped
      full-chip netlist). Sky130 cannot close spec 1.25 GHz; that is a
      known node risk, not a missing report file.
EOF

if [ -n "$SDC" ] && [ -f "$SDC" ]; then
  cp -f "$SDC" "$OUT_DIR/$(basename "$SDC")"
fi

if [ "$ys_rc" -ne 0 ]; then
  echo "Yosys failed (rc=$ys_rc). See $LOG" >&2
  exit "$ys_rc"
fi

echo "synth ok  top=$TOP  netlist=$NETLIST  reports=$RPT_DIR"
