# OpenSTA post-synth (or later signoff) driver.
# Env: TOP LIBERTY NETLIST SDC RPT_DIR
# Writes reports/signoff/sta_wns_tns.rpt. Does not invent numbers.

set top     $::env(TOP)
set liberty $::env(LIBERTY)
set netlist $::env(NETLIST)
set sdc     $::env(SDC)
set rptdir  $::env(RPT_DIR)

if {![file exists $liberty]} {
  puts "ERROR: liberty not found: $liberty"
  exit 2
}
if {![file exists $netlist]} {
  puts "ERROR: netlist not found: $netlist"
  puts "Run make -C impl synth-smoke or synth first."
  exit 2
}
if {![file exists $sdc]} {
  puts "ERROR: SDC not found: $sdc"
  exit 2
}

file mkdir $rptdir

read_liberty $liberty
read_verilog $netlist
link_design $top
read_sdc $sdc

set sta_rpt [file join $rptdir sta_wns_tns.rpt]
set chk_rpt [file join $rptdir sta_checks.rpt]

set f [open $sta_rpt w]
puts $f "design   $top"
puts $f "netlist  $netlist"
puts $f "sdc      $sdc"
puts $f "liberty  $liberty"
puts $f "tapeout  no"
puts $f "NOTE: Sky130 + spec 1.25 GHz is not a closed timing signoff."
puts $f ""
puts $f "==== report_wns / report_tns ===="
close $f

# OpenSTA prints WNS/TNS to stdout (captured in sta.log by the wrapper).
report_wns
report_tns

if {[catch {redirect $chk_rpt { report_checks -path_delay min_max -digits 3 }} err]} {
  puts "NOTE: report_checks redirect failed ($err); see sta.log"
}

set f [open $sta_rpt a]
puts $f "(numeric WNS/TNS are in sta.log — generated by OpenSTA, not hand-typed)"
puts $f "checks   $chk_rpt"
close $f
