#!/usr/bin/env bash
# Yosys synthesis driver for Vibe-UB-Switch.
# Generates reports under reports/synth/. Does not invent QoR numbers.
# Liberty mapping is optional: if no Sky130 liberty is found, synth stays
# generic (cell counts only; no Sky130 area).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TOP="${TOP:-vibe_ub_switch}"
INC_DIR="${INC_DIR:-$ROOT/rtl/common}"
RPT_DIR="${RPT_DIR:-$ROOT/reports/synth}"
OUT_DIR="${OUT_DIR:-$ROOT/impl/work}"
SDC="${SDC:-}"
LIBERTY="${LIBERTY:-}"
YOSYS="${YOSYS:-yosys}"

if [ "$#" -lt 1 ]; then
  echo "usage: $0 <verilog-file> [verilog-file...]" >&2
  echo "env: TOP INC_DIR RPT_DIR OUT_DIR SDC LIBERTY YOSYS" >&2
  exit 2
fi

if ! command -v "$YOSYS" >/dev/null 2>&1; then
  cat >&2 <<'EOF'
Yosys not found.

Install (pick one), then re-run:

  # Debian/Ubuntu (generic Yosys; enough for synth-smoke)
  sudo apt-get update && sudo apt-get install -y yosys

  # ORFS prebuilts (Yosys + OpenROAD + OpenSTA)
  # https://openroad-flow-scripts.readthedocs.io/en/latest/user/BuildWithPrebuilt.html

  # ORFS Docker
  # https://openroad-flow-scripts.readthedocs.io/en/latest/user/BuildWithDocker.html

  # From source via ORFS
  git clone --recursive https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts.git
  # then follow docs/user/BuildLocally.md

Do not copy PDK / liberty / LEF binaries into this repo.
EOF
  exit 2
fi

mkdir -p "$RPT_DIR" "$OUT_DIR"

YS="$OUT_DIR/${TOP}.ys"
NETLIST="$OUT_DIR/${TOP}.synth.v"
LOG="$RPT_DIR/synth.log"

# --- write Yosys script ---------------------------------------------------
{
  echo "# Generated by impl/yosys/run_synth.sh — do not hand-edit."
  echo "logger -notime"
  echo "echo on"
  for f in "$@"; do
    printf 'read_verilog -sv -I %s %s\n' "$INC_DIR" "$f"
  done
  echo "hierarchy -check -top $TOP"
  echo "synth -top $TOP"
  if [ -n "$LIBERTY" ]; then
    echo "dfflibmap -liberty $LIBERTY"
    echo "abc -liberty $LIBERTY"
    echo "opt_clean"
    echo "tee -o $RPT_DIR/stat.rpt stat -liberty $LIBERTY"
  else
    echo "tee -o $RPT_DIR/stat.rpt stat"
  fi
  echo "tee -o $RPT_DIR/hierarchy.rpt hierarchy -check -top $TOP"
  echo "write_verilog -noattr $NETLIST"
} > "$YS"

# --- flow_info (generated; no fabricated metrics) -------------------------
{
  echo "design              $TOP"
  echo "repo_root           $ROOT"
  echo "repo_sha            $(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
  echo "rtl_frozen          no  (coverage still open; not a QoR signoff SHA)"
  echo "yosys               $($YOSYS -V 2>/dev/null | head -n 1 || echo unknown)"
  echo "sdc                 ${SDC:-none}"
  echo "liberty             ${LIBERTY:-none (generic cells; not Sky130 area)}"
  echo "netlist             $NETLIST"
  echo "platform            sky130hd (ORFS name; only if liberty was provided)"
  echo "tapeout             no"
  echo "note                Sky130 cannot close spec 1.25 GHz. Flow bring-up only."
} > "$RPT_DIR/flow_info.txt"

set +e
"$YOSYS" -s "$YS" > "$LOG" 2>&1
ys_rc=$?
set -e

# --- derived reports from Yosys output (still generated) ------------------
if [ -f "$RPT_DIR/stat.rpt" ]; then
  grep -E 'Number of |Chip area|Estimated number of LCs|wires:|cells:|[[:space:]]+\$_' \
    "$RPT_DIR/stat.rpt" > "$RPT_DIR/cells.rpt" || true
  if grep -q 'Chip area' "$RPT_DIR/stat.rpt"; then
    grep -E 'Chip area|Number of cells' "$RPT_DIR/stat.rpt" > "$RPT_DIR/area.rpt"
  else
    cat > "$RPT_DIR/area.rpt" <<EOF
STATUS: generic_synth
NOTE: No liberty was passed to Yosys, so there is no Sky130 area figure.
      Cell counts are in $RPT_DIR/stat.rpt / cells.rpt.
      Do not invent an area number. Re-run with LIBERTY=... or make orfs-synth.
EOF
  fi
else
  echo "STATUS: synth_failed" > "$RPT_DIR/area.rpt"
  echo "STATUS: synth_failed" > "$RPT_DIR/cells.rpt"
fi

cat > "$RPT_DIR/timing_summary.rpt" <<EOF
STATUS: not_run_by_yosys
NOTE: Yosys synth does not produce WNS/TNS.
      After a mapped netlist + liberty exist, run: make -C impl sta
      Do not invent STA numbers here.
EOF

if [ -n "$SDC" ] && [ -f "$SDC" ]; then
  cp -f "$SDC" "$OUT_DIR/$(basename "$SDC")"
fi

if [ "$ys_rc" -ne 0 ]; then
  echo "Yosys failed (rc=$ys_rc). See $LOG" >&2
  exit "$ys_rc"
fi

echo "synth ok  top=$TOP  netlist=$NETLIST  reports=$RPT_DIR"
