"""Fabric / DLL / mgmt / NW / LMSM unit TCs. Same RTL lists as run_units.sh."""

from pathlib import Path

from catalog_pcs import _no_input_default

ROOT = Path(__file__).resolve().parents[3]
PY = Path(__file__).resolve().parent
def _wrap(name):
    return str(PY / "tb" / f"{name}.sv")


def _w(*p):
    return str(ROOT.joinpath("rtl", *p))


FAB = [
    _w("fabric", "vibe_saf_ing.sv"),
    _w("fabric", "vibe_route_lu.sv"),
    _w("fabric", "vibe_port_sel.sv"),
    _w("fabric", "vibe_xbar.sv"),
    _w("fabric", "vibe_voq_egr.sv"),
    _w("fabric", "vibe_vl_rr.sv"),
    _w("fabric", "vibe_fecn_mark.sv"),
    _w("fabric", "vibe_fabric.sv"),
]
MGMT = [
    _w("mgmt", "vibe_mgmt.sv"),
    _w("mgmt", "vibe_cfg_space.sv"),
    _w("mgmt", "vibe_cna_ep.sv"),
    _w("mgmt", "vibe_irq_agg.sv"),
    _w("mgmt", "vibe_rst_ctl.sv"),
]
DLL_RX = [_w("dll", "vibe_dll_rx.sv")]
DLL_ACK = [_w("dll", "vibe_dll_retry_ack_sm.sv")]
DLL_BUF = [_w("dll", "vibe_dll_retry_buf.sv")]
RETRY_REQ = [_w("dll", "vibe_dll_retry_req_sm.sv")]
DLL_WRAP = [
    _w("dll", "vibe_dll.sv"),
    _w("dll", "vibe_dll_sm.sv"),
    _w("dll", "vibe_dll_credit.sv"),
    _w("dll", "vibe_dll_retry_buf.sv"),
    _w("dll", "vibe_dll_retry_req_sm.sv"),
    _w("dll", "vibe_dll_retry_ack_sm.sv"),
    _w("dll", "vibe_dll_tx.sv"),
    _w("dll", "vibe_dll_rx.sv"),
    _w("dll", "vibe_bcrc.sv"),
]
# Same filelist as catalog.PORT_RTL (avoid circular import).
PORT_WRAP = [
    _w("cdc", "vibe_sync2.sv"),
    _w("cdc", "vibe_afifo.sv"),
    _w("cdc", "vibe_rst_sync.sv"),
    _w("cdc", "vibe_gear_160_128.sv"),
    _w("cdc", "vibe_gear_128_160.sv"),
    _w("pma", "vibe_pma_bnd.sv"),
    _w("pcs", "vibe_pcs_tx.sv"),
    _w("pcs", "vibe_pcs_tx_g1.sv"),
    _w("pcs", "vibe_pcs_tx_fec.sv"),
    _w("pcs", "vibe_rs128_120_enc.sv"),
    _w("pcs", "vibe_pcs_tx_cw2beat.sv"),
    _w("pcs", "vibe_pcs_tx_pack.sv"),
    _w("pcs", "vibe_pcs_tx_amctl.sv"),
    _w("pcs", "vibe_ebch16.sv"),
    _w("pcs", "vibe_pcs_scramble.sv"),
    _no_input_default("pcs", "vibe_pcs_rx.sv"),
    _w("pcs", "vibe_pcs_rx_amctl_lock.sv"),
    _w("pcs", "vibe_pcs_rx_deskew.sv"),
    _no_input_default("pcs", "vibe_pcs_rx_unpack.sv"),
    _no_input_default("pcs", "vibe_pcs_rx_fec.sv"),
    _w("pcs", "vibe_rs128_120_dec.sv"),
    _w("lmsm", "vibe_lmsm.sv"),
    _w("dll", "vibe_dll.sv"),
    _w("dll", "vibe_dll_sm.sv"),
    _w("dll", "vibe_dll_credit.sv"),
    _w("dll", "vibe_dll_retry_buf.sv"),
    _w("dll", "vibe_dll_retry_req_sm.sv"),
    _w("dll", "vibe_dll_retry_ack_sm.sv"),
    _w("dll", "vibe_dll_tx.sv"),
    _w("dll", "vibe_dll_rx.sv"),
    _w("dll", "vibe_bcrc.sv"),
    _w("nw", "vibe_nw_adapt.sv"),
    _w("port", "vibe_port.sv"),
]
# Decision-I stage-44 wrap leaf. Same children as catalog.TOP_RTL.
TOP_WRAP = PORT_WRAP + FAB + MGMT + [
    _w("mgmt", "vibe_mgmt_byp.sv"),
    _w("top", "vibe_ub_switch.sv"),
]
# Decision-I stage-47 wrap leaf. Product vibe_pcs_tx + stock children.
# Do not pull lmsm (HOLD).
PCS_TX = [
    _w("pcs", "vibe_pcs_tx.sv"),
    _w("pcs", "vibe_pcs_tx_g1.sv"),
    _w("pcs", "vibe_pcs_tx_fec.sv"),
    _w("pcs", "vibe_rs128_120_enc.sv"),
    _w("pcs", "vibe_pcs_tx_cw2beat.sv"),
    _w("pcs", "vibe_pcs_tx_pack.sv"),
    _w("pcs", "vibe_pcs_tx_amctl.sv"),
    _w("pcs", "vibe_ebch16.sv"),
    _w("pcs", "vibe_pcs_scramble.sv"),
]
# Decision-I stage-48 wrap leaf. Product vibe_pcs_rx + stock children.
# Do not pull lmsm (HOLD). link_up / unpack / fec input defaults
# stripped for Verilator 5.020 (same as PORT_WRAP / leaf RX units).
PCS_RX = [
    _no_input_default("pcs", "vibe_pcs_rx.sv"),
    _w("pcs", "vibe_pcs_rx_amctl_lock.sv"),
    _w("pcs", "vibe_ebch16.sv"),
    _w("pcs", "vibe_pcs_scramble.sv"),
    _w("pcs", "vibe_pcs_rx_deskew.sv"),
    _no_input_default("pcs", "vibe_pcs_rx_unpack.sv"),
    _no_input_default("pcs", "vibe_pcs_rx_fec.sv"),
]
# Decision-I stage-49 wrap leaf. Product vibe_lmsm is an FSM leaf
# (CHILDREN empty — no child RTL). Do not invent hierarchy.
LMSM = [
    _w("lmsm", "vibe_lmsm.sv"),
]

UNIT_MORE = [
    ("tc_irq_agg", "vibe_irq_agg", [_w("mgmt", "vibe_irq_agg.sv")], "entry_unit"),
    ("tc_rst_port_device", "vibe_rst_ctl", [_w("mgmt", "vibe_rst_ctl.sv")], "entry_unit"),
    ("tc_fecn_mark", "vibe_fecn_mark", [_w("fabric", "vibe_fecn_mark.sv")], "entry_unit"),
    ("tc_credit_grain_n", "vibe_dll_credit", [_w("dll", "vibe_dll_credit.sv")], "entry_unit"),
    ("tc_credit_no_underflow", "vibe_dll_credit", [_w("dll", "vibe_dll_credit.sv")], "entry_unit"),
    ("tc_nw_adapt_linkready", "vibe_nw_adapt", [_w("nw", "vibe_nw_adapt.sv")], "entry_unit"),
    ("tc_phy_nw_dll_512b", "vibe_nw_adapt", [_w("nw", "vibe_nw_adapt.sv")], "entry_unit"),
    ("tc_saf_ing", "vibe_saf_ing", [_w("fabric", "vibe_saf_ing.sv")], "entry_unit"),
    ("tc_voq_rd", "vibe_voq_egr", [_w("fabric", "vibe_voq_egr.sv")], "entry_unit"),
    ("tc_dll_sm_states", "vibe_dll_sm", [_w("dll", "vibe_dll_sm.sv")], "entry_unit"),
    ("tc_mgmt_byp", "vibe_mgmt_byp", [_w("mgmt", "vibe_mgmt_byp.sv")], "entry_unit"),
    ("tc_xbar_unit", "vibe_xbar_cocotb_top",
     [_wrap("vibe_xbar_cocotb_top"), _w("fabric", "vibe_xbar.sv")], "entry_unit"),
    ("tc_cna_ep", "vibe_cna_ep_cocotb_top",
     [_wrap("vibe_cna_ep_cocotb_top"), _w("mgmt", "vibe_cna_ep.sv")], "entry_unit"),
    ("tc_credit_timeout_1us", "vibe_dll_credit", [_w("dll", "vibe_dll_credit.sv")], "entry_unit"),
    ("tc_deadlock_timeout_1us", "vibe_voq_egr", [_w("fabric", "vibe_voq_egr.sv")], "entry_unit"),
    ("tc_retry_buf_256", "vibe_dll_retry_buf", [_w("dll", "vibe_dll_retry_buf.sv")], "entry_unit"),
    ("tc_retry_req_gbn", "vibe_retry_req_cocotb_top",
     [_wrap("vibe_retry_req_cocotb_top")] + RETRY_REQ, "entry_unit"),
    ("tc_retry_ack_replay", "vibe_dll_retry_ack_sm", DLL_ACK, "entry_unit"),
    ("tc_retry_wait_retrain", "vibe_retry_req_cocotb_top",
     [_wrap("vibe_retry_req_cocotb_top")] + RETRY_REQ, "entry_unit"),
    ("tc_icrc_txrx_vs_transit", "vibe_icrc", [_w("nw", "vibe_icrc.sv")], "entry_unit"),
    ("tc_pma_512b_slice", "vibe_pma_bnd", [_w("pma", "vibe_pma_bnd.sv")], "entry_unit"),
    ("tc_afifo_afull10", "vibe_afifo",
     [_w("cdc", "vibe_afifo.sv"), _w("cdc", "vibe_sync2.sv")], "entry_unit"),
    ("tc_vibe_afifo", "vibe_afifo_cocotb_top",
     [_wrap("vibe_afifo_cocotb_top"),
      _w("cdc", "vibe_afifo.sv"), _w("cdc", "vibe_sync2.sv")], "entry_unit"),
    ("tc_vibe_sync2", "vibe_sync2_cocotb_top",
     [_wrap("vibe_sync2_cocotb_top"), _w("cdc", "vibe_sync2.sv")], "entry_unit"),
    ("tc_vibe_rst_sync", "vibe_rst_sync_cocotb_top",
     [_wrap("vibe_rst_sync_cocotb_top"), _w("cdc", "vibe_rst_sync.sv")], "entry_unit"),
    ("tc_vibe_gear_128_160", "vibe_gear_128_160_cocotb_top",
     [_wrap("vibe_gear_128_160_cocotb_top"), _w("cdc", "vibe_gear_128_160.sv")],
     "entry_unit"),
    ("tc_vibe_gear_160_128", "vibe_gear_160_128_cocotb_top",
     [_wrap("vibe_gear_160_128_cocotb_top"), _w("cdc", "vibe_gear_160_128.sv")],
     "entry_unit"),
    ("tc_vibe_pcs_scramble", "vibe_pcs_scramble_cocotb_top",
     [_wrap("vibe_pcs_scramble_cocotb_top"), _w("pcs", "vibe_pcs_scramble.sv")],
     "entry_unit"),
    ("tc_vibe_ebch16", "vibe_ebch16_cocotb_top",
     [_wrap("vibe_ebch16_cocotb_top"), _w("pcs", "vibe_ebch16.sv")],
     "entry_unit"),
    ("tc_vibe_pcs_tx_cw2beat", "vibe_pcs_tx_cw2beat_cocotb_top",
     [_wrap("vibe_pcs_tx_cw2beat_cocotb_top"), _w("pcs", "vibe_pcs_tx_cw2beat.sv")],
     "entry_unit"),
    ("tc_vibe_pcs_tx_amctl", "vibe_pcs_tx_amctl_cocotb_top",
     [_wrap("vibe_pcs_tx_amctl_cocotb_top"),
      _w("pcs", "vibe_pcs_tx_amctl.sv"), _w("pcs", "vibe_ebch16.sv")],
     "entry_unit"),
    ("tc_vibe_rs128_120_enc", "vibe_rs128_120_enc_cocotb_top",
     [_wrap("vibe_rs128_120_enc_cocotb_top"),
      _w("pcs", "vibe_rs128_120_enc.sv")],
     "entry_unit"),
    ("tc_vibe_rs128_120_dec", "vibe_rs128_120_dec_cocotb_top",
     [_wrap("vibe_rs128_120_dec_cocotb_top"),
      _w("pcs", "vibe_rs128_120_dec.sv")],
     "entry_unit"),
    ("tc_vibe_pcs_rx_deskew", "vibe_pcs_rx_deskew_cocotb_top",
     [_wrap("vibe_pcs_rx_deskew_cocotb_top"),
      _w("pcs", "vibe_pcs_rx_deskew.sv")],
     "entry_unit"),
    ("tc_vibe_pcs_rx_amctl_lock", "vibe_pcs_rx_amctl_lock_cocotb_top",
     [_wrap("vibe_pcs_rx_amctl_lock_cocotb_top"),
      _w("pcs", "vibe_pcs_rx_amctl_lock.sv"), _w("pcs", "vibe_ebch16.sv")],
     "entry_unit"),
    ("tc_vibe_pcs_rx_unpack", "vibe_pcs_rx_unpack_cocotb_top",
     [_wrap("vibe_pcs_rx_unpack_cocotb_top"),
      _no_input_default("pcs", "vibe_pcs_rx_unpack.sv")],
     "entry_unit"),
    ("tc_vibe_pcs_tx_pack", "vibe_pcs_tx_pack_cocotb_top",
     [_wrap("vibe_pcs_tx_pack_cocotb_top"),
      _w("pcs", "vibe_pcs_tx_pack.sv"),
      _w("pcs", "vibe_pcs_tx_amctl.sv"),
      _w("pcs", "vibe_ebch16.sv")],
     "entry_unit"),
    ("tc_vibe_pcs_tx_fec", "vibe_pcs_tx_fec_cocotb_top",
     [_wrap("vibe_pcs_tx_fec_cocotb_top"),
      _w("pcs", "vibe_pcs_tx_fec.sv"),
      _w("pcs", "vibe_rs128_120_enc.sv")],
     "entry_unit"),
    ("tc_vibe_pcs_rx_fec", "vibe_pcs_rx_fec_cocotb_top",
     [_wrap("vibe_pcs_rx_fec_cocotb_top"),
      _no_input_default("pcs", "vibe_pcs_rx_fec.sv")],
     "entry_unit"),
    ("tc_vibe_pcs_tx_g1", "vibe_pcs_tx_g1_cocotb_top",
     [_wrap("vibe_pcs_tx_g1_cocotb_top"),
      _w("pcs", "vibe_pcs_tx_g1.sv")],
     "entry_unit"),
    ("tc_vibe_bcrc", "vibe_bcrc_cocotb_top",
     [_wrap("vibe_bcrc_cocotb_top"),
      _w("dll", "vibe_bcrc.sv")],
     "entry_unit"),
    ("tc_vibe_dll_credit", "vibe_dll_credit_cocotb_top",
     [_wrap("vibe_dll_credit_cocotb_top"),
      _w("dll", "vibe_dll_credit.sv")],
     "entry_unit"),
    ("tc_vibe_dll_sm", "vibe_dll_sm_cocotb_top",
     [_wrap("vibe_dll_sm_cocotb_top"),
      _w("dll", "vibe_dll_sm.sv")],
     "entry_unit"),
    ("tc_vibe_dll_rx", "vibe_dll_rx_cocotb_top",
     [_wrap("vibe_dll_rx_cocotb_top")] + DLL_RX,
     "entry_unit"),
    ("tc_vibe_dll_retry_ack_sm", "vibe_dll_retry_ack_sm_cocotb_top",
     [_wrap("vibe_dll_retry_ack_sm_cocotb_top")] + DLL_ACK,
     "entry_unit"),
    ("tc_vibe_dll_retry_buf", "vibe_dll_retry_buf_cocotb_top",
     [_wrap("vibe_dll_retry_buf_cocotb_top")] + DLL_BUF,
     "entry_unit"),
    ("tc_vibe_dll_retry_req_sm", "vibe_dll_retry_req_sm_cocotb_top",
     [_wrap("vibe_dll_retry_req_sm_cocotb_top")] + RETRY_REQ,
     "entry_unit"),
    ("tc_vibe_fecn_mark", "vibe_fecn_mark_cocotb_top",
     [_wrap("vibe_fecn_mark_cocotb_top"), _w("fabric", "vibe_fecn_mark.sv")],
     "entry_unit"),
    ("tc_vibe_vl_rr", "vibe_vl_rr_cocotb_top",
     [_wrap("vibe_vl_rr_cocotb_top"), _w("fabric", "vibe_vl_rr.sv")],
     "entry_unit"),
    ("tc_vibe_route_lu", "vibe_route_lu_cocotb_top",
     [_wrap("vibe_route_lu_cocotb_top"), _w("fabric", "vibe_route_lu.sv")],
     "entry_unit"),
    ("tc_vibe_port_sel", "vibe_port_sel_cocotb_top",
     [_wrap("vibe_port_sel_cocotb_top"), _w("fabric", "vibe_port_sel.sv")],
     "entry_unit"),
    ("tc_vibe_voq_egr", "vibe_voq_egr_cocotb_top",
     [_wrap("vibe_voq_egr_cocotb_top"), _w("fabric", "vibe_voq_egr.sv")],
     "entry_unit"),
    ("tc_vibe_saf_ing", "vibe_saf_ing_cocotb_top",
     [_wrap("vibe_saf_ing_cocotb_top"), _w("fabric", "vibe_saf_ing.sv")],
     "entry_unit"),
    ("tc_vibe_xbar", "vibe_xbar_cocotb_top",
     [_wrap("vibe_xbar_cocotb_top"), _w("fabric", "vibe_xbar.sv")],
     "entry_unit"),
    ("tc_vibe_dll_tx", "vibe_dll_tx_cocotb_top",
     [_wrap("vibe_dll_tx_cocotb_top"), _w("dll", "vibe_dll_tx.sv")],
     "entry_unit"),
    # Decision-I stage-77 wrap leaf. Not TP-DLL-004 (that stays tc_dll).
    ("tc_vibe_dll", "vibe_dll_cocotb_top",
     [_wrap("vibe_dll_cocotb_top")] + DLL_WRAP, "entry_unit"),
    # Decision-I stage-36 module leaf. Not wrap-style tc_icrc_txrx_vs_transit.
    ("tc_vibe_icrc", "vibe_icrc_cocotb_top",
     [_wrap("vibe_icrc_cocotb_top"), _w("nw", "vibe_icrc.sv")],
     "entry_unit"),
    # Decision-I stage-40 module leaf. Not wrap-style tc_irq_agg / vibe_mgmt.
    ("tc_vibe_irq_agg", "vibe_irq_agg_cocotb_top",
     [_wrap("vibe_irq_agg_cocotb_top"), _w("mgmt", "vibe_irq_agg.sv")],
     "entry_unit"),
    # Decision-I stage-41 module leaf. Not wrap-style tc_cna_ep / vibe_mgmt.
    ("tc_vibe_cna_ep", "vibe_cna_ep_cocotb_top",
     [_wrap("vibe_cna_ep_cocotb_top"), _w("mgmt", "vibe_cna_ep.sv")],
     "entry_unit"),
    # Decision-I stage-42 module leaf. Not wrap-style tc_identity_cfg_space.
    ("tc_vibe_cfg_space", "vibe_cfg_space_cocotb_top",
     [_wrap("vibe_cfg_space_cocotb_top"), _w("mgmt", "vibe_cfg_space.sv")],
     "entry_unit"),
    # Decision-I stage-50 wrap leaf (tip-align after stages 47–49).
    # Not TP-PHY / tc_port_smoke (that stays make port). CHILDREN from SV.
    ("tc_vibe_port", "vibe_port_wrap_cocotb_top",
     [_wrap("vibe_port_wrap_cocotb_top")] + PORT_WRAP, "entry_unit"),
    # Decision-I stage-44 wrap leaf. Not tc_top_smoke (that stays make top).
    ("tc_vibe_ub_switch", "vibe_ub_switch_wrap_cocotb_top",
     [_wrap("vibe_ub_switch_wrap_cocotb_top")] + TOP_WRAP, "entry_unit"),
    # Decision-I stage-45 wrap leaf. Not wrap-style tc_mgmt (that stays vibe_mgmt top).
    ("tc_vibe_mgmt", "vibe_mgmt_wrap_cocotb_top",
     [_wrap("vibe_mgmt_wrap_cocotb_top")] + MGMT, "entry_unit"),
    # Decision-I stage-46 wrap leaf. Not wrap-style fabric suite (that stays entry_fab).
    ("tc_vibe_fabric", "vibe_fabric_wrap_cocotb_top",
     [_wrap("vibe_fabric_wrap_cocotb_top")] + FAB, "entry_unit"),
    # Decision-I stage-47 wrap leaf. Not Icarus full-stack tc_pcs_tx.
    ("tc_vibe_pcs_tx", "vibe_pcs_tx_wrap_cocotb_top",
     [_wrap("vibe_pcs_tx_wrap_cocotb_top")] + PCS_TX, "entry_unit"),
    # Decision-I stage-48 wrap leaf. Not Icarus full-stack tc_pcs_rx.
    ("tc_vibe_pcs_rx", "vibe_pcs_rx_wrap_cocotb_top",
     [_wrap("vibe_pcs_rx_wrap_cocotb_top")] + PCS_RX, "entry_unit"),
    # Decision-I stage-49 wrap leaf. FSM leaf; CHILDREN empty.
    # Not stock Icarus / pyuvm tc_lmsm_walk (that stays vibe_lmsm top).
    ("tc_vibe_lmsm", "vibe_lmsm_wrap_cocotb_top",
     [_wrap("vibe_lmsm_wrap_cocotb_top")] + LMSM, "entry_unit"),
    ("tc_lmsm_walk", "vibe_lmsm", [_w("lmsm", "vibe_lmsm.sv")], "entry_unit"),
    ("tc_lmsm_vlock", "vibe_lmsm", [_w("lmsm", "vibe_lmsm.sv")], "entry_unit"),
    ("tc_lmsm_cc", "vibe_lmsm", [_w("lmsm", "vibe_lmsm.sv")], "entry_unit"),
    ("tc_cfg0_term_not_fabric", "vibe_dll_rx_cocotb_top",
     [_wrap("vibe_dll_rx_cocotb_top")] + DLL_RX, "entry_unit"),
    ("tc_dll_rx_errflag", "vibe_dll_rx_cocotb_top",
     [_wrap("vibe_dll_rx_cocotb_top")] + DLL_RX, "entry_unit"),
    ("tc_fec_fail_gbn", "vibe_dll_rx_cocotb_top",
     [_wrap("vibe_dll_rx_cocotb_top")] + DLL_RX, "entry_unit"),
    ("tc_rt_g1_official", "vibe_rt_g1_cocotb_top",
     [_wrap("vibe_rt_g1_cocotb_top"), _w("fabric", "vibe_route_lu.sv"),
      _w("fabric", "vibe_port_sel.sv")],
     "entry_unit"),
    ("tc_dll_tx_cfg0", "vibe_dll_tx_cfg0_cocotb_top",
     [_wrap("vibe_dll_tx_cfg0_cocotb_top"), _w("dll", "vibe_dll_tx.sv"),
      _w("dll", "vibe_bcrc.sv"), _w("dll", "vibe_dll_credit.sv")], "entry_unit"),
    # TP-DLL-004: full vibe_dll wrapper. Leaf SM/credit/retry/rx/tx are not enough.
    ("tc_dll", "vibe_dll_cocotb_top",
     [_wrap("vibe_dll_cocotb_top")] + DLL_WRAP, "entry_unit"),
    ("tc_mgmt", "vibe_mgmt", MGMT, "entry_unit"),
    ("tc_timers_indep", "vibe_timers_indep_cocotb_top",
     [_wrap("vibe_timers_indep_cocotb_top"),
      _w("dll", "vibe_dll_credit.sv"), _w("fabric", "vibe_voq_egr.sv")],
     "entry_unit"),
]
