#!/usr/bin/env python3
"""Scan rtl/vibe_*.sv for official TP-NEG / absent-feature identifiers.

Writes a SystemVerilog include of hit flags. Comment-only prohibition
lines (No / not / do not / absent / unimpl) do not count as hits.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

# (sv_localparam, official TP name printed by TC, regex)
RULES = [
    ("HIT_UB3", "tc_id_spec_2_0_only", r"\bUB_BASE_3\b|\bub_base_3\b|\bUB3_ONLY\b"),
    ("HIT_APXD", "tc_id_appendix_d_subset", r"\bQDLWS\b|\bqdlws_|\bAPPENDIX_D_FULL\b"),
    ("HIT_SL", "tc_vl_no_sl", r"\bSL_MAP\b|\bsl_to_vl\b|\bservice_level\b"),
    ("HIT_CAQM", "tc_fecn_no_caqm", r"\bCAQM\b|\bcaqm_"),
    ("HIT_NPI", "tc_qos_npi_disabled", r"\bnpi_filter\b|\bnpi_en\b|\bNPI_FILTER\b"),
    ("HIT_UPI", "tc_nw_no_upi_port_ip", r"\bUPI_ROUTE\b|\bport_ip_lu\b|\bPortIP\b"),
    ("HIT_HOP", "tc_fab_no_hop_qdepth_must", r"\bhop_cnt\b|\bqdepth_must\b|\bHOP_COUNT\b"),
    ("HIT_HOTPLUG", "tc_irq_no_hotplug", r"\bhotplug\b|\bhot_plug\b"),
    ("HIT_ATTACK", "tc_err_no_attack_req", r"\battack_detect\b|\bintrusion_det\b"),
    ("HIT_XPORT", "tc_neg_no_transport_ep",
     r"\btransport_ep\b|\btransaction_layer\b|\bfunction_ep\b"),
    ("HIT_UMMU", "tc_neg_no_ummu", r"\bUMMU\b|\bummu_"),
    ("HIT_UBOE", "tc_neg_no_uboe", r"\bUBoE\b|\buboe_"),
    ("HIT_ANA", "tc_neg_no_analog_pma",
     r"\bgray_map\b|\bprecoder\b|\bserdes_ana\b|\bANALOG_PMA\b"),
    ("HIT_SECRET", "tc_neg_no_secret_ip", r"\bsecret_ip\b|\bencrypted_core\b"),
    ("HIT_HCSR", "tc_neg_no_host_csr", r"\bapb_paddr\b|\baxi4_\b|\bhost_csr_"),
    ("HIT_OFFCHIP", "tc_neg_no_offchip_mgmt", r"\bi2c_sda\b|\bjtag_tck\b|\boffchip_mgmt\b"),
    ("HIT_README", "tc_neg_no_readme_numbers", r"\bOLD_README\b|\bub_v0_nport\b"),
    ("HIT_FS7", "tc_neg_no_fs7_bundle", r"\bFS7_\b|\bfs7_bundle\b"),
    ("HIT_P5", "tc_neg_no_fifth_port", r"\btxdata_4\b|\brxdata_4\b|\bvibe_port_4\b"),
]

COMMENT_OK = re.compile(
    r"(?i)(no |not |don't |do not|absent|unimpl|forbidden|void|never |not a )"
)


def code_part(line: str) -> str:
    if "//" in line:
        return line.split("//", 1)[0]
    return line


def scan(rtl: Path) -> dict[str, list[str]]:
    hits: dict[str, list[str]] = {name: [] for name, _, _ in RULES}
    files = sorted(rtl.rglob("vibe_*.sv")) + sorted(rtl.rglob("vibe_*.vh"))
    compiled = [(name, re.compile(pat)) for name, _, pat in RULES]
    for fp in files:
        try:
            text = fp.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for i, raw in enumerate(text.splitlines(), 1):
            code = code_part(raw)
            if not code.strip():
                continue
            if COMMENT_OK.search(raw) and "//" in raw:
                # prohibition comment — ignore even if token leaked before //
                if not code.strip() or COMMENT_OK.search(code):
                    continue
            for name, rx in compiled:
                if rx.search(code):
                    hits[name].append(f"{fp}:{i}:{raw.strip()[:80]}")
    return hits


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("rtl")
    ap.add_argument("--inc", required=True)
    args = ap.parse_args()
    rtl = Path(args.rtl)
    if not rtl.is_dir():
        Path(args.inc).write_text(
            "// scan failed\nlocalparam integer NEG_SCAN_OPEN_FAIL = 1;\n"
            + "".join(f"localparam integer {n} = 1;\n" for n, _, _ in RULES),
            encoding="utf-8",
        )
        return 2
    hits = scan(rtl)
    lines = ["// generated by scan_official_neg.py — do not edit",
             "localparam integer NEG_SCAN_OPEN_FAIL = 0;"]
    for name, _, _ in RULES:
        lines.append(f"localparam integer {name} = {1 if hits[name] else 0};")
    Path(args.inc).parent.mkdir(parents=True, exist_ok=True)
    Path(args.inc).write_text("\n".join(lines) + "\n", encoding="utf-8")
    und = 0
    crd = rtl / "dll" / "vibe_dll_credit.sv"
    if crd.is_file():
        for raw in crd.read_text(encoding="utf-8", errors="replace").splitlines():
            code = raw.split("//", 1)[0]
            if re.search(r"underflow|und_err|credit_und", code, re.I):
                und = 1
                break
    (Path(args.inc).parent / "und_scan.inc").write_text(
        f"localparam integer UND_CODE_HIT = {und};\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
